//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMATEC.WASmatec.WSRefSMATEC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSRefSMATEC.IRecopiladorDatosRest")]
    public interface IRecopiladorDatosRest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecopiladorDatosRest/SetData", ReplyAction="http://tempuri.org/IRecopiladorDatosRest/SetDataResponse")]
        bool SetData(string CadenaLectura);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecopiladorDatosRestChannel : SMATEC.WASmatec.WSRefSMATEC.IRecopiladorDatosRest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecopiladorDatosRestClient : System.ServiceModel.ClientBase<SMATEC.WASmatec.WSRefSMATEC.IRecopiladorDatosRest>, SMATEC.WASmatec.WSRefSMATEC.IRecopiladorDatosRest {
        
        public RecopiladorDatosRestClient() {
        }
        
        public RecopiladorDatosRestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecopiladorDatosRestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecopiladorDatosRestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecopiladorDatosRestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SetData(string CadenaLectura) {
            return base.Channel.SetData(CadenaLectura);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSRefSMATEC.IRecopiladorDatosTeselador")]
    public interface IRecopiladorDatosTeselador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecopiladorDatosTeselador/TeselarData", ReplyAction="http://tempuri.org/IRecopiladorDatosTeselador/TeselarDataResponse")]
        void TeselarData();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecopiladorDatosTeseladorChannel : SMATEC.WASmatec.WSRefSMATEC.IRecopiladorDatosTeselador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecopiladorDatosTeseladorClient : System.ServiceModel.ClientBase<SMATEC.WASmatec.WSRefSMATEC.IRecopiladorDatosTeselador>, SMATEC.WASmatec.WSRefSMATEC.IRecopiladorDatosTeselador {
        
        public RecopiladorDatosTeseladorClient() {
        }
        
        public RecopiladorDatosTeseladorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecopiladorDatosTeseladorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecopiladorDatosTeseladorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecopiladorDatosTeseladorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TeselarData() {
            base.Channel.TeselarData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSRefSMATEC.IRecopiladorDatos")]
    public interface IRecopiladorDatos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecopiladorDatos/GetServiceDescriptionInfo", ReplyAction="http://tempuri.org/IRecopiladorDatos/GetServiceDescriptionInfoResponse")]
        string GetServiceDescriptionInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecopiladorDatos/GetLecturas", ReplyAction="http://tempuri.org/IRecopiladorDatos/GetLecturasResponse")]
        string[] GetLecturas(string IdEquipo, SMATEC.Periodicidad Periodicidad, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecopiladorDatos/GetEquipos", ReplyAction="http://tempuri.org/IRecopiladorDatos/GetEquiposResponse")]
        SMATEC.DescripcionEquipo[] GetEquipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecopiladorDatos/GetCurrent", ReplyAction="http://tempuri.org/IRecopiladorDatos/GetCurrentResponse")]
        string[] GetCurrent();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecopiladorDatosChannel : SMATEC.WASmatec.WSRefSMATEC.IRecopiladorDatos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecopiladorDatosClient : System.ServiceModel.ClientBase<SMATEC.WASmatec.WSRefSMATEC.IRecopiladorDatos>, SMATEC.WASmatec.WSRefSMATEC.IRecopiladorDatos {
        
        public RecopiladorDatosClient() {
        }
        
        public RecopiladorDatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecopiladorDatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecopiladorDatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecopiladorDatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetServiceDescriptionInfo() {
            return base.Channel.GetServiceDescriptionInfo();
        }
        
        public string[] GetLecturas(string IdEquipo, SMATEC.Periodicidad Periodicidad, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.GetLecturas(IdEquipo, Periodicidad, FechaInicio, FechaFin);
        }
        
        public SMATEC.DescripcionEquipo[] GetEquipos() {
            return base.Channel.GetEquipos();
        }
        
        public string[] GetCurrent() {
            return base.Channel.GetCurrent();
        }
    }
}
